/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef User_TYPES_H
#define User_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <thrift/cxxfunctional.h>


namespace com { namespace baichebao { namespace service {

class User;

typedef struct _User__isset {
  _User__isset() : uid(false), email(false), uname(false), usex(false), uage(false) {}
  bool uid :1;
  bool email :1;
  bool uname :1;
  bool usex :1;
  bool uage :1;
} _User__isset;

class User {
 public:

  static const char* ascii_fingerprint; // = "E1429FBEB33B4FF8E9E97EDE493A31C0";
  static const uint8_t binary_fingerprint[16]; // = {0xE1,0x42,0x9F,0xBE,0xB3,0x3B,0x4F,0xF8,0xE9,0xE9,0x7E,0xDE,0x49,0x3A,0x31,0xC0};

  User(const User&);
  User& operator=(const User&);
  User() : uid(0), email(), uname(), usex(0), uage(0) {
  }

  virtual ~User() throw();
  int32_t uid;
  std::string email;
  std::string uname;
  bool usex;
  int16_t uage;

  _User__isset __isset;

  void __set_uid(const int32_t val);

  void __set_email(const std::string& val);

  void __set_uname(const std::string& val);

  void __set_usex(const bool val);

  void __set_uage(const int16_t val);

  bool operator == (const User & rhs) const
  {
    if (!(uid == rhs.uid))
      return false;
    if (!(email == rhs.email))
      return false;
    if (!(uname == rhs.uname))
      return false;
    if (!(usex == rhs.usex))
      return false;
    if (!(uage == rhs.uage))
      return false;
    return true;
  }
  bool operator != (const User &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const User & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const User& obj);
};

void swap(User &a, User &b);

}}} // namespace

#endif
